- src/commands/main.js
- src/commands/shard.js
Before
main.js
shard.js
After
main.js
shard.js
> fix(main|shard): Missing awaits

- src/commands/main.js
> feat: supporting kurasuta shard manager

- src/index.js
Missing alias param Options
In result alias init is not working.
so fix it.
**Status**
> fix: add aliases param to option

- package.json
> Move discord.js dependency to DevDependency

- package.json
Missed to update version in package.json
> WHATS THE PROBLEM WITH YOU?

- src/commands/js.js
- src/utils/index.js
- src/utils/isGenerator.js
Resolve generators and send it to channel.
Example:
```md
// Input
.dok js (function* () {
yield 1
yield 2
yield 3
})()
```
```md
// Output
1
2
3
```
**Status**
> Resolve generators

- LICENSE
- examples/bot.js
- package.json
- src/commands/cat.js
- src/commands/curl.js
- src/commands/exec.js
- src/commands/js.js
- src/commands/jsi.js
- src/commands/shard.js
- src/index.js
- src/utils/ProcessManager.js
- src/utils/index.js
- src/utils/isGenerator.js
- typings/index.d.ts
- yarn.lock
Fixed some bugs and added global variable
> 0.3.0 Release

- .github/workflows/testing-cron.yml
- .github/workflows/testing.yml
- package.json
- yarn.lock
Fixing issues like #28 
> Originally from #73 by @zero734kr 
**Status**
> fix: discord.js to peer deps

- src/index.js
**Status**
I think ready event once is enough.
It canbe memory leak.
> fix: change ready event once

- package.json
- src/utils/ProcessManager.js
- src/utils/index.js
- src/utils/regexpEscape.js
- test/Utils.ProcessManager.test.js
> Fix secret not hidden at special char

- src/index.js
> chore: parsing commands from module

- src/commands/main.js
- src/utils/DateFormatting.js
- src/utils/index.js
- src/utils/relativeTime.js
> refactor(DateFormatting): changed structure

- src/utils/djsDocs.js
> fix(djsDocs): change branch from master to main

- src/index.js
> Add exec case

- src/utils/djsDocs.js
> Fixed error occurring on docs command when result is not found

- src/utils/djsDocs.js
Closes #279
**Status**
> `discord.js@dev`
> `discord.js@latest`
> fix(djsdocs): return main branch if version includes dev

- src/utils/djsDocs.js
> Fixing error on docs command

- src/utils/count.js
> fix(jsi): constructor is called though element is null

- src/index.js
> fix: main command displayed at root

- examples/bot.js
- package.json
- src/commands/main.js
- src/utils/index.js
- src/utils/join.js
> Release v0.6

- .github/workflows/npm-publish.yml
> cd: added npm publish

- typings/index.d.ts
> fix: noPerm option to optional

- .github/workflows/npm-publish.yml
- .github/workflows/testing.yml
- package.json
> ci: fixed publish build

- src/utils/ProcessManager.ts
- Fixes Unknown Message error raised on .edit()
**Status**
> fix: handle error on edit
